### ISSUE TITLE
useSWRをたくさん呼び出すと、「android.net.ConnectivityManager$TooManyRequestsException 」によってクラッシュする(If call useSWR many times, crashing by android.net.ConnectivityManager$TooManyRequestsException)

### ISSUE THREAD

**Issue by wintermaples** [KazaKago/swr-compose#35]
## Jp:
useSWRをたくさん呼び出すと、「android.net.ConnectivityManager$TooManyRequestsException 」によってクラッシュします。

これは、revalidateOnReconnectオプションがtrueだと、UseSWROptions.RevalidateOnReconnectの、LifecycleEventObserver内にあるregisterNetworkCallbackを多量に登録していることに起因していると考えられます。

networkCallbackを一度だけ登録するようにすれば改善すると考えられますがどうでしょうか？

## En:
If call useSWR many times, crashing by android.net.ConnectivityManager$TooManyRequestsException 

This problem caused by calling registerNetworkCallback too many times in UseSWROptions.RevalidateOnReconnect -> LifecycleEventObserver if revalidateOnReconnect = true.

Maybe, This problem will be fixed by chaning code to register networkCallback once only.

Please someone's opinion.

<details>
<summary>Code:</summary>

UseSWROptions.RevalidateOnReconnect
```kotlin
 val lifecycleObserver = LifecycleEventObserver { _, event ->
                when (event) {
                    Lifecycle.Event.ON_START -> {
                        shouldNotValidateAtNextOnAvailable = connectivityManager.getNetworkCapabilities(connectivityManager.activeNetwork)?.let {
                            it.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET) && it.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED)
                        } ?: false
                        connectivityManager.registerNetworkCallback(request, networkCallback) <-- Here!
                    }
                    Lifecycle.Event.ON_STOP -> {
                        connectivityManager.unregisterNetworkCallback(networkCallback)
                    }
                    else -> {}
                }
            }
```
</details>

<details>
<summary>StackTrace:</summary>

```
android.net.ConnectivityManager$TooManyRequestsException
at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4034)
at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4226)
at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4233)
at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4615)
at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4585)
at com.kazakago.swr.compose.internal.UseSWROptionsKt$RevalidateOnReconnect$1.invoke$lambda$1(UseSWROptions.kt:125)
at com.kazakago.swr.compose.internal.UseSWROptionsKt$RevalidateOnReconnect$1.$r8$lambda$dDbd31SUo6_iOlvK8STGeUnEKlA(Unknown Source:0)
at com.kazakago.swr.compose.internal.UseSWROptionsKt$RevalidateOnReconnect$1$$ExternalSyntheticLambda0.onStateChanged(Unknown Source:10)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
at com.kazakago.swr.compose.internal.UseSWROptionsKt$RevalidateOnReconnect$1.invoke(UseSWROptions.kt:133)
at com.kazakago.swr.compose.internal.UseSWROptionsKt$RevalidateOnReconnect$1.invoke(UseSWROptions.kt:103)
at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1091)
at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:585)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:503)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
at android.view.Choreographer.doCallbacks(Choreographer.java:899)
at android.view.Choreographer.doFrame(Choreographer.java:827)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@ae3b631, androidx.compose.ui.platform.MotionDurationScaleImpl@f5db116, StandaloneCoroutine{Cancelling}@3dd4a97, AndroidUiDispatcher@9bcf484]
```
</details>

**Comment by KazaKago** [comment]
遅くなってすみません、issueの起案ありがとうございます！
たしかに仰るとおりですね
`android.net.ConnectivityManager$TooManyRequestsException` は見落としておりました。

提案いただいた内容をもとに修正いたしますのでしばらくお待ち下さい。

-----

Sorry for the delay, thanks for drafting the issue!
You are absolutely right.
I missed `android.net.ConnectivityManager$TooManyRequestsException.`

Please wait a moment while we fix it.

**Comment by KazaKago** [comment]
本件はバージョン0.6.2にて修正いたしました

------

This issue has been fixed in 0.6.2.
